spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/msa
    username: '{cipher}af0d56faa8017c6b1df203203c4e392532311ba5bc15681fd7a1592090691206'
    password:
    driver-class-name: org.h2.Driver

order_service:
  url: http://order-service/order-service/%s/orders
  exception:
    orders_is_empty: User's orders is empty.